kind: Pod
apiVersion: v1
metadata:
  name: iraj-dummy-pod
spec:
  containers:
    - name: iraj-dummy-pod
      image: hedayati/toolset:latest
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: Never